### PR TITLE
Upgrade to Laravel 8

### PR DESCRIPTION
**Pull request by SamuelMwangiW**
Upgrade the application to laravel 8

### CODE REVIEW

**Comment by youcefSpring** [comment]
the problem is when we execute npm run watch  it's very slowly
any solution ??

Le mer. 13 janv. 2021 à 19:50, Samuel Mwangi <notifications@github.com> a
écrit :

**Comment by SamuelMwangiW** [comment]
@youcefSpring allow me test that. I only upgraded laravel-mix to 6. Laravel 8 swapped from sass to postcss.

**Comment by youcefSpring** [comment]
From the first time not just from today

**Comment by SamuelMwangiW** [comment]
Your issue is not related to this PR. Kindly open an issue.

**Comment by youcefSpring** [comment]
look it's stay like thike this all the time
[image: image.png]

Le jeu. 14 janv. 2021 à 05:35, Samuel Mwangi <notifications@github.com> a
écrit :

**Pull request closed without merging**
